[package]
distribution = "2201.13.4"
org = "avi0ra"
name = "huggingface"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Hasitha Erandika"]
keywords = ["huggingface", "ai", "llm", "inference", "machine-learning", "nlp"]

repository = "https://github.com/HasithaErandika/avi0ra-huggingface"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
