[package]
distribution = "2201.13.4"
org = "avi0ra"
name = "huggingface"
version = "1.1.1"
license = ["Apache-2.0"]
authors = ["Hasitha Erandika"]
keywords = ["huggingface", "ai", "llm", "inference", "machine-learning", "nlp", "rag", "streaming"]
icon = "icon.png"
repository = "https://github.com/HasithaErandika/avi0ra-huggingface"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true