// Generated by Ballerina OpenAPI tool and manually sanitized.
// See docs/spec/sanitations.md for changes made post-generation.

import ballerina/url;

# Get Encoded URI for a given value.
#
# + value - Value to be encoded
# + return - Encoded string
isolated function getEncodedUri(anydata value) returns string {
    string|error encoded = url:encode(value.toString(), "UTF8");
    if encoded is string {
        return encoded;
    } else {
        return value.toString();
    }
}
